name: Atualização Diária do Panorama

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4

      - name: Executar script de atualização
        run: python update.py

      - name: Commit e push
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add index.html || echo "Nada para adicionar"
          git commit -m "Atualização automática do panorama" || echo "Nada para commitar"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

..